import React from 'react';
import { BrowserRouter as Router, Route, Routes } from 'react-router-dom';
import Header from './components/ID_Header';
import Content from './components/Home/ID_Content';
import Visual from './components/Details/visual';
import ChartsContainer from './components/Summary/ChartsContainer';
import './App.css';

// Imports the Amplify library from 'aws-amplify' package. This is used to configure your app to interact with AWS services.
import { Amplify } from 'aws-amplify';

// Imports the Authenticator and withAuthenticator components from '@aws-amplify/ui-react'.
// Authenticator is a React component that provides a ready-to-use sign-in and sign-up UI.
// withAuthenticator is a higher-order component that wraps your app component to enforce authentication.
import { Authenticator, withAuthenticator } from '@aws-amplify/ui-react';

// Imports the default styles for the Amplify UI components. This line ensures that the authenticator looks nice out of the box.
import '@aws-amplify/ui-react/styles.css';

// Imports the awsExports configuration file generated by the Amplify CLI. This file contains the AWS service configurations (like Cognito, AppSync, etc.) specific to your project.
import awsExports from './aws-exports';

// Configures the Amplify library with the settings from aws-exports.js, which includes all the AWS service configurations for this project.
Amplify.configure(awsExports);



const App = () => {

  return (

    <div className="App">
      <Authenticator>
        {({ signOut }) => (
          <main>
            <header className='App-header'>
              <Router>
                <div className="app-container">
                  <Header />
                  <div className="main-content">

                    <Routes>
                      <Route path="/" element={<Content />} />
                      <Route path="/home" element={<ChartsContainer />} />
                      <Route path="/profile/:kolId" element={<Visual />} />
                    </Routes>

                  </div>
                </div>
              </Router>
              <button
                onClick={signOut}
                style={{
                  margin: '20px',
                  fontSize: '0.8rem',
                  padding: '5px 10px',
                  marginTop: '20px'
                }}
              >
                Sign Out
              </button>
            </header>
          </main>
        )}
      </Authenticator>
    </div>
  );
}

export default withAuthenticator(App);




